
import "./globals.css";
import Providers from "@/components/ui/provider";
import SideBar from "@/components/SideBar";
import TopBar from "@/components/TopBar";
import { Box } from "@chakra-ui/react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <SideBar />
          <Box
            flex={1}
          >
            <TopBar />
            {children}

          </Box>
        </Providers>
      </body>
    </html>
  );
}
