
import "./globals.css";
import Providers from "@/components/ui/provider";
import SideBar from "@/components/SideBar";
import TopBar from "@/components/TopBar";
import { Box, Flex } from "@chakra-ui/react";
import AddBookmarkModal from "@/components/client/AddBookmarkModal";
import { BookmarkProvider } from "@/context/BookmarkContext";
import { UserContextProvider } from "@/context/UserContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <UserContextProvider>
          <BookmarkProvider>

            <Providers>
              <TopBar />
              <Flex
                position={"relative"}
                h={"100vh"}
                w={"full"}
              >
                <SideBar />
                {children}
              </Flex>
              <AddBookmarkModal />
            </Providers>
            
          </BookmarkProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
