export const Tags = [
    "Frameworks",
    "AI",
    "Compatibility",
    "Community",
    "CSS",
    "Design",
    "Git",
    "HTML",
    "JavaScript",
    "Layout",
    "Learning",
    "Performance",
    "Practice",
    "Reference",
    "Tips",
    "Tools",
    "Tutorials"
]